---
- name: Ensure namespace exists
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ rhbk_project_name }}'
        annotations:
          openshift.io/display-name: '{{ rhbk_project_display }}'
      spec: {}

- name: Subscribe to RH Keycloak Operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhbk-operator.yml.j2")|from_yaml }}'

- name: Wait for RH Keycloak Operator to finish being created
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: v1
    kind: Pod
    namespace: '{{ rhbk_project_name }}'
    label_selectors:
      - "name = rhbk-operator"
  register: rhbk_op_pod
  until: rhbk_op_pod.resources|length > 0 and (rhbk_op_pod.resources|first).status.phase == "Running"
  retries: 20
  delay: 30
