---
## Create Realm and Configure Openshift IDP
- name: Check for ConfigMap with CA bundle
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: v1
    kind: ConfigMap
    namespace: openshift-config
    name: ca-config-map
  register: configmap_present
  when:
  - not trusted_router_certificates|bool

- name: Fail if the configmap isn't present and it should be
  fail:
    msg: >
      Before you can create the RH-SSO Identity Provider for OpenShift,
      you must upload the CA that signs your publicly-accessible certificates
      for cluster services (specifically, the console) for redirects to work.
      Please name the bundle `ca-config-map` in the `openshift-config` Project.
  when:
  - not trusted_router_certificates|bool
  - configmap_present.resources|length < 1

- name: Create client secret for openshift realm
  ansible.builtin.command: oc create secret generic {{ rhbk_project_name}}-client-secret
    --from-literal=clientSecret={{ generated_password }}
    -n openshift-config
  ignore_errors: true

- name: Create RH Keycloak IdP in OpenShift
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhbk-ocp-idp.yml.j2")|from_yaml }}'

- name: Set ocp console logout redirect to sso logout endpoint
  k8s: 
    kubeconfig: '{{ kubeconfig }}'
    state: present
    api_version: config.openshift.io/v1
    kind: Console
    name: cluster
    definition:
      spec:
        authentication:
          logoutRedirect: 'https://{{ rhbk_hostname }}/auth/realms/{{ rhbk_realm_name }}/protocol/openid-connect/logout?post_logout_redirect_uri=https%3A%2F%2Fconsole-openshift-console.apps.{{ subdomain }}&client_id=openshift'

