---
- name: Create RH Keycloak Deployment
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhbk-deployment.yml.j2")|from_yaml }}'

- name: Wait for RH Keycloak to finish being created
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: v1
    kind: Pod
    namespace: '{{ rhbk_project_name }}'
    label_selectors:
      - "app = keycloak"
  register: rhbk_pod
  until: rhbk_pod.resources|length > 0 and (rhbk_pod.resources|first).status.phase == "Running"
  retries: 20
  delay: 30

- name: Create Realm
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhbk-ocp-realm.yml.j2")|from_yaml }}'
