---
#TODO: Add cluster role to admin users
- name: TODO- Add cluster-admin to admin users
  ansible.builtin.command:
    oc adm policy add-cluster-role-to-user cluster-admin "{{ item.username }}"
  loop: "{{ rhbk_users }}"
  when: item.admin | default(false) | bool
