---
- name: Ensure that the cluster tmp directory exists
  file:
    path: '{{ tmp_dir }}'
    state: directory

- include_tasks: issuecerts.yml
  when:
    - issuecerts
    - AWS_ACCESS_KEY_ID is defined or ansible_env["AWS_ACCESS_KEY_ID"] is defined
