---
- name: Ensure namespace exists
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: '{{ rhsso_project_name }}'
        annotations:
          openshift.io/display-name: '{{ rhsso_project_display }}'
      spec: {}

- name: Subscribe to RH-SSO Operator
  k8s:
    kubeconfig: '{{ kubeconfig }}'
    definition: '{{ lookup("template", "rhsso-operator.yml.j2")|from_yaml }}'

- name: Wait for RH-SSO Operator to finish being created
  k8s_info:
    kubeconfig: '{{ kubeconfig }}'
    api_version: v1
    kind: Pod
    namespace: '{{ rhsso_project_name }}'
    label_selectors:
      - "name=rhsso-operator"
  register: rhsso_op_pod
  until: rhsso_op_pod.resources|length > 0 and (rhsso_op_pod.resources|first).status.phase == "Running"
  retries: 20
  delay: 30
