---
- hosts: localhost
  pre_tasks:
    - name: Look for default defined common variables
      include_vars: ../vars/common.yml
      when: common_included is not defined or not common_included

    - fail:
        msg: Unable to continue without common variables set
      when: common_included is not defined or not common_included

    - name: Look for default defined quickstart variables
      include_vars: ../vars/quickstart.yml
      when: quickstart_included is not defined or not quickstart_included

    - fail:
        msg: Unable to continue without devsecops variables set
      when: quickstart_included is not defined or not quickstart_included

  roles:
    - role: quickstart
