---
- hosts: localhost
  pre_tasks:
    - name: Look for default defined common variables
      include_vars: ../vars/common.yml
      when: common_included is not defined or not common_included

    - fail:
        msg: Unable to continue without common variables set
      when: common_included is not defined or not common_included

    - name: Look for default defined provision variables
      include_vars: ../vars/provision.yml
      when: provision_included is not defined or not provision_included

    - fail:
        msg: Unable to continue without provision variables set
      when: provision_included is not defined or not provision_included

  tasks:
    - include_role:
        name: rhsso

      
